
#ident "$Id$"

#include "TimeZoneRegistry.h"
#include "Exception.h"


// initialize static members
pthread_mutex_t TimeZoneRegistry::mutex = PTHREAD_MUTEX_INITIALIZER;
bool TimeZoneRegistry::initialized = false;
TimeZoneMap TimeZoneRegistry::_timeZoneMap;

// return the offset of the location in hours relative to GMT
int TimeZoneRegistry::getOffset (char *location)
{
  pthread_mutex_lock (&mutex);
  if ( ! initialized)
    {
      initialize();
    }
  
  TimeZoneMap::iterator timeZoneMapIterator = _timeZoneMap.find (location);
  pthread_mutex_unlock (&mutex);

  if (timeZoneMapIterator == _timeZoneMap.end())
    {
      throw Exception (__FILE__, __LINE__, 
                       "Unknown location: %s",
                       location);
    }

  return timeZoneMapIterator->second;
}

void TimeZoneRegistry::initialize (void)
{
  _timeZoneMap["Albania"] = 1;
  _timeZoneMap["Algeria"] = 1;
  _timeZoneMap["American Samoa"] = -11;
  _timeZoneMap["Andorra"] = 1;
  _timeZoneMap["Angola"] = 1;
  _timeZoneMap["Anguilla"] = -4;
  _timeZoneMap["Antarctica"] = -2;
  _timeZoneMap["Antigua"] = -4;
  _timeZoneMap["Argentina"] = -3;
  _timeZoneMap["Argentina western prov"] = -4;
  _timeZoneMap["Armenia"] = 4;
  _timeZoneMap["Aruba"] = -4;
  _timeZoneMap["Ascension"] = 0;
  _timeZoneMap["Australia Western"] = 8;
  _timeZoneMap["Australia New South Wales"] = 10;
  _timeZoneMap["Australia Queensland"] = 10;
  _timeZoneMap["Australia Victoria"] = 10;
  _timeZoneMap["Australian Capital Territory"] = 10;
  _timeZoneMap["Australia Tasmania"] = 10;
  _timeZoneMap["Austria"] = 1;
  _timeZoneMap["Azerbaijan"] = 3;
  _timeZoneMap["Azores"] = -1;
  _timeZoneMap["Bahamas"] = -5;
  _timeZoneMap["Bahrain"] = 3;
  _timeZoneMap["Balearic Islands"] = 1;
  _timeZoneMap["Bangladesh"] = 6;
  _timeZoneMap["Barbados"] = -4;
  _timeZoneMap["Belarus"] = 2;
  _timeZoneMap["Belgium"] = 1;
  _timeZoneMap["Belize"] = -6;
  _timeZoneMap["Benin"] = 1;
  _timeZoneMap["Bermuda"] = -4;
  _timeZoneMap["Bhutan"] = 6;
  _timeZoneMap["Bolivia"] = -4;
  _timeZoneMap["Bonaire"] = -4;
  _timeZoneMap["Bosnia Hercegovina"] = 1;
  _timeZoneMap["Botswana"] = 2;
  _timeZoneMap["Brazil West"] = -4;
  _timeZoneMap["Brazil Acre"] = -4;
  _timeZoneMap["Brazil East"] = -3;
  _timeZoneMap["Brazil Atlantic Islands"] = -1;
  _timeZoneMap["British Virgin Islands"] = -4;
  _timeZoneMap["Brunei"] = 8;
  _timeZoneMap["Bulgaria"] = 2;
  _timeZoneMap["Burkina Faso"] = 0;
  _timeZoneMap["Burundi"] = 2;
  _timeZoneMap["Cambodia"] = 7;
  _timeZoneMap["Cameroon"] = 1;
  _timeZoneMap["Canada Yukon &Pacific"] = -8;
  _timeZoneMap["Canada Mountain"] = -7;
  _timeZoneMap["Canada Central"] = -6;
  _timeZoneMap["Canada Eastern"] = -5;
  _timeZoneMap["Canada Atlantic"] = -4;
  _timeZoneMap["Canary Islands"] = 0;
  _timeZoneMap["Canton Enderbury Islands"] = -11;
  _timeZoneMap["Cape Verde"] = -1;
  _timeZoneMap["Caroline Island"] = 11;
  _timeZoneMap["Cayman Islands"] = -5;
  _timeZoneMap["Central African Rep"] = 1;
  _timeZoneMap["Chad"] = 1;
  _timeZoneMap["Channel Islands"] = 0;
  _timeZoneMap["Chile"] = -4;
  _timeZoneMap["China People's Rep"] = 8;
  _timeZoneMap["Christmas Islands"] = -10;
  _timeZoneMap["Colombia"] = -5;
  _timeZoneMap["Congo"] = 1;
  _timeZoneMap["Cook Islands"] = -10;
  _timeZoneMap["Costa Rica"] = -6;
  _timeZoneMap["Cote d'Ivoire"] = 0;
  _timeZoneMap["Croatia"] = 1;
  _timeZoneMap["Cuba"] = -5;
  _timeZoneMap["Curacao"] = -4;
  _timeZoneMap["Cyprus"] = 2;
  _timeZoneMap["Czech Republic"] = 1;
  _timeZoneMap["Dahomey"] = 1;
  _timeZoneMap["Denmark"] = 1;
  _timeZoneMap["Djibouti"] = 3;
  _timeZoneMap["Dominica"] = -4;
  _timeZoneMap["Dominican Republic"] = -4;
  _timeZoneMap["Easter Island"] = -6;
  _timeZoneMap["Ecuador"] = -5;
  _timeZoneMap["Egypt"] = 2;
  _timeZoneMap["El Salvador"] = -6;
  _timeZoneMap["England"] = 0;
  _timeZoneMap["Equatorial Guinea"] = 1;
  _timeZoneMap["Eritrea"] = 3;
  _timeZoneMap["Estonia"] = 2;
  _timeZoneMap["Ethiopia"] = 3;
  _timeZoneMap["Falkland Islands"] = -4;
  _timeZoneMap["Faroe Island"] = 0;
  _timeZoneMap["Fiji"] = 12;
  _timeZoneMap["Finland"] = 2;
  _timeZoneMap["France"] = 1;
  _timeZoneMap["French Guiana"] = -3;
  _timeZoneMap["French Polynesia"] = -10;
  _timeZoneMap["Gabon"] = 1;
  _timeZoneMap["Galapagos Islands"] = -5;
  _timeZoneMap["Gambia"] = 0;
  _timeZoneMap["Gambier Island"] = -9;
  _timeZoneMap["Georgia"] = 4;
  _timeZoneMap["Germany"] = 1;
  _timeZoneMap["Ghana"] = 0;
  _timeZoneMap["Gibraltar"] = 1;
  _timeZoneMap["Greece"] = 2;
  _timeZoneMap["Greenland"] = -3;
  _timeZoneMap["Greenland Thule"] = -4;
  _timeZoneMap["Greenland Scoresbysun"] = -1;
  _timeZoneMap["Grenada"] = -4;
  _timeZoneMap["Grenadines"] = -4;
  _timeZoneMap["Guadeloupe"] = -4;
  _timeZoneMap["Guam"] = 10;
  _timeZoneMap["Guatemala"] = -6;
  _timeZoneMap["Guinea"] = 0;
  _timeZoneMap["Guinea Bissau"] = -1;
  _timeZoneMap["Guyana"] = -3;
  _timeZoneMap["Haiti"] = -5;
  _timeZoneMap["Honduras"] = -6;
  _timeZoneMap["Hong Kong"] = 8;
  _timeZoneMap["Hungary"] = 1;
  _timeZoneMap["Iceland"] = 0;
  _timeZoneMap["Indonesia West"] = 7;
  _timeZoneMap["Indonesia Central"] = 8;
  _timeZoneMap["Indonesia East"] = 9;
  _timeZoneMap["Iraq"] = 3;
  _timeZoneMap["Ireland Republic of"] = 0;
  _timeZoneMap["Israel"] = 2;
  _timeZoneMap["Italy"] = 1;
  _timeZoneMap["Jamaica"] = -5;
  _timeZoneMap["Japan"] = 9;
  _timeZoneMap["Johnston Island"] = -10;
  _timeZoneMap["Jordan"] = 2;
  _timeZoneMap["Kazakhstan"] = 6;
  _timeZoneMap["Kenya"] = 3;
  _timeZoneMap["Kiribati"] = 12;
  _timeZoneMap["Korea Dem Republic of"] = 9;
  _timeZoneMap["Korea Republic of"] = 9;
  _timeZoneMap["Kusaie"] = 12;
  _timeZoneMap["Kuwait"] = 3;
  _timeZoneMap["Kwajalein"] = 12;
  _timeZoneMap["Kyrgyzstan"] = 5;
  _timeZoneMap["Laos"] = 7;
  _timeZoneMap["Latvia"] = 2;
  _timeZoneMap["Lebanon"] = 2;
  _timeZoneMap["Leeward Islands"] = -4;
  _timeZoneMap["Lesotho"] = 2;
  _timeZoneMap["Liberia"] = 0;
  _timeZoneMap["Libya"] = 2;
  _timeZoneMap["Lithuania"] = 2;
  _timeZoneMap["Luxembourg"] = 1;
  _timeZoneMap["Macedonia"] = 1;
  _timeZoneMap["Madagascar"] = 3;
  _timeZoneMap["Madeira"] = 0;
  _timeZoneMap["Malawi"] = 2;
  _timeZoneMap["Malaysia"] = 8;
  _timeZoneMap["Maldives"] = 5;
  _timeZoneMap["Mali"] = 0;
  _timeZoneMap["Mallorca Islands"] = 1;
  _timeZoneMap["Malta"] = 1;
  _timeZoneMap["Mariana Island"] = 10;
  _timeZoneMap["Marshall Islands"] = 12;
  _timeZoneMap["Martinique"] = -4;
  _timeZoneMap["Mauritania"] = 0;
  _timeZoneMap["Mauritius"] = 4;
  _timeZoneMap["Mayotte"] = 3;
  _timeZoneMap["Melilla"] = 1;
  _timeZoneMap["Mexico"] = -6;
  _timeZoneMap["Mexico Baja Calif Norte"] = -8;
  _timeZoneMap["Mexico Nayarit"] = -7;
  _timeZoneMap["Mexico Sinaloa"] = -7;
  _timeZoneMap["Mexico Sonora"] = -7;
  _timeZoneMap["Midway Island"] = -11;
  _timeZoneMap["Moldova"] = 2;
  _timeZoneMap["Moldovian Rep Pridnestrovye"] = 2;
  _timeZoneMap["Monaco"] = 1;
  _timeZoneMap["Mongolia"] = 8;
  _timeZoneMap["Morocco"] = 0;
  _timeZoneMap["Mozambique"] = 2;
  _timeZoneMap["Namibia"] = 1;
  _timeZoneMap["Nauru Republic of"] = 12;
  _timeZoneMap["Netherlands"] = 1;
  _timeZoneMap["Netherlands Antilles"] = -4;
  _timeZoneMap["Nevis Montserrat"] = -4;
  _timeZoneMap["New Caledonia"] = 11;
  _timeZoneMap["New Hebrides"] = 11;
  _timeZoneMap["New Zealand"] = 12;
  _timeZoneMap["Nicaragua"] = -6;
  _timeZoneMap["Niger"] = 1;
  _timeZoneMap["Nigeria"] = 1;
  _timeZoneMap["Niue Island"] = -11;
  _timeZoneMap["Northern Ireland"] = 0;
  _timeZoneMap["Northern Mariana Islands"] = 10;
  _timeZoneMap["Norway"] = 1;
  _timeZoneMap["Oman"] = 4;
  _timeZoneMap["Pakistan"] = 5;
  _timeZoneMap["Palau"] = 9;
  _timeZoneMap["Panama"] = -5;
  _timeZoneMap["Papua New Guinea"] = 10;
  _timeZoneMap["Paraguay"] = -4;
  _timeZoneMap["Peru"] = -5;
  _timeZoneMap["Philippines"] = 8;
  _timeZoneMap["Pingelap"] = 12;
  _timeZoneMap["Poland"] = 1;
  _timeZoneMap["Ponape Island"] = 11;
  _timeZoneMap["Portugal"] = 1;
  _timeZoneMap["Principe Island"] = 0;
  _timeZoneMap["Puerto Rico"] = -4;
  _timeZoneMap["Qatar"] = 3;
  _timeZoneMap["Reunion"] = 4;
  _timeZoneMap["Romania"] = 2;
  _timeZoneMap["Russian Federation zone one"] = 2;
  _timeZoneMap["Russian Federation zone two"] = 3;
  _timeZoneMap["Russian Federation zone three"] = 4;
  _timeZoneMap["Russian Federation zone four"] = 5;
  _timeZoneMap["Russian Federation zone five"] = 6;
  _timeZoneMap["Russian Federation zone six"] = 7;
  _timeZoneMap["Russian Federation zone seven"] = 8;
  _timeZoneMap["Russian Federation zone eight"] = 9;
  _timeZoneMap["Russian Federation zone nine"] = 10;
  _timeZoneMap["Russian Federation zone ten"] = 11;
  _timeZoneMap["Russian Federation zone eleven"] = 12;
  _timeZoneMap["Rwanda"] = 2;
  _timeZoneMap["Saba"] = -4;
  _timeZoneMap["Samoa"] = -11;
  _timeZoneMap["San Marino"] = 1;
  _timeZoneMap["Sao Tome e Principe"] = 0;
  _timeZoneMap["Saudi Arabia"] = 3;
  _timeZoneMap["Scotland"] = 0;
  _timeZoneMap["Senegal"] = 0;
  _timeZoneMap["Seychelles"] = 4;
  _timeZoneMap["Sierra Leone"] = 0;
  _timeZoneMap["Singapore"] = 8;
  _timeZoneMap["Slovakia"] = 1;
  _timeZoneMap["Slovenia"] = 1;
  _timeZoneMap["Society Island"] = -10;
  _timeZoneMap["Solomon Islands"] = 11;
  _timeZoneMap["Somalia"] = 3;
  _timeZoneMap["South Africa"] = 2;
  _timeZoneMap["Spain"] = 1;
  _timeZoneMap["St Christopher"] = -4;
  _timeZoneMap["St Croix"] = -4;
  _timeZoneMap["St Helena"] = 0;
  _timeZoneMap["St John"] = -4;
  _timeZoneMap["St Kitts Nevis"] = -4;
  _timeZoneMap["St Lucia"] = -4;
  _timeZoneMap["St Maarten"] = -4;
  _timeZoneMap["St Pierre &Miquelon"] = -3;
  _timeZoneMap["St Thomas"] = -4;
  _timeZoneMap["St Vincent"] = -4;
  _timeZoneMap["Sudan"] = 2;
  _timeZoneMap["Suriname"] = -3;
  _timeZoneMap["Swaziland"] = 2;
  _timeZoneMap["Sweden"] = 1;
  _timeZoneMap["Switzerland"] = 1;
  _timeZoneMap["Syria"] = 2;
  _timeZoneMap["Tahiti"] = -10;
  _timeZoneMap["Taiwan"] = 8;
  _timeZoneMap["Tajikistan"] = 6;
  _timeZoneMap["Tanzania"] = 3;
  _timeZoneMap["Thailand"] = 7;
  _timeZoneMap["Togo"] = 0;
  _timeZoneMap["Tonga"] = 13;
  _timeZoneMap["Trinidad and Tobago"] = -4;
  _timeZoneMap["Tuamotu Island"] = -10;
  _timeZoneMap["Tubuai Island"] = -10;
  _timeZoneMap["Tunisia"] = 1;
  _timeZoneMap["Turkey"] = 2;
  _timeZoneMap["Turkmenistan"] = 5;
  _timeZoneMap["Turks and Caicos Islands"] = -5;
  _timeZoneMap["Tuvalu"] = 12;
  _timeZoneMap["Uganda"] = 3;
  _timeZoneMap["Ukraine"] = 2;
  _timeZoneMap["United Arab Emirates"] = 4;
  _timeZoneMap["United Kingdom"] = 0;
  _timeZoneMap["USA Aleutian"] = -10;
  _timeZoneMap["USA Hawaii"] = -10;
  _timeZoneMap["USA Alaska"] = -9;
  _timeZoneMap["USA Pacific"] = -8;
  _timeZoneMap["USA Mountain"] = -7;
  _timeZoneMap["USA Arizona"] = -7;
  _timeZoneMap["USA Central"] = -6;
  _timeZoneMap["USA Eastern"] = -5;
  _timeZoneMap["USA Indiana East"] = -5;
  _timeZoneMap["Uruguay"] = -3;
  _timeZoneMap["Uzbekistan"] = 5;
  _timeZoneMap["Vanuatu"] = 11;
  _timeZoneMap["Vatican City"] = 1;
  _timeZoneMap["Venezuela"] = -4;
  _timeZoneMap["Vietnam"] = 7;
  _timeZoneMap["Virgin Islands"] = -4;
  _timeZoneMap["Wake Island"] = 12;
  _timeZoneMap["Wales"] = 0;
  _timeZoneMap["Wallis and Futuna Islands"] = 12;
  _timeZoneMap["Windward Islands"] = -4;
  _timeZoneMap["Yemen"] = 3;
  _timeZoneMap["Yugoslavia"] = 1;
  _timeZoneMap["Zaire Kinshasa Mbandaka"] = 1;
  _timeZoneMap["Zaire Kasai"] = 2;
  _timeZoneMap["Zaire Haut Zaire"] = 2;
  _timeZoneMap["Zaire Kivu"] = 2;
  _timeZoneMap["Zaire Shaba"] = 2;
  _timeZoneMap["Zambia"] = 2;
  _timeZoneMap["Zimbabwe"] = 2;
}  
